
import mongoose from "mongoose";
import dotenv from "dotenv";
import Call from "../src/models/Call.js";

dotenv.config();

const testSave = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        console.log("✅ Connected to MongoDB");

        // 1. Find a recent ongoing call (or creates one if none)
        let call = await Call.findOne({ status: 'ongoing' }).sort({ createdAt: -1 });

        if (!call) {
            console.log("No ongoing call found, creating a dummy one...");
            // Need dummy IDs. Use random ObjectIds
            const dummyUser1 = new mongoose.Types.ObjectId();
            const dummyUser2 = new mongoose.Types.ObjectId();
            call = await Call.create({
                roomId: "test-room-" + Date.now(),
                participants: [dummyUser1, dummyUser2],
                type: "video" // or audio
            });
            console.log("Created dummy call:", call._id);
        } else {
            console.log("Using existing call:", call._id);
        }

        // 2. Try to push a transcript
        const testTranscript = {
            sender: call.participants[0], // Use first participant as sender
            text: "This is a TEST transcript generated by the verification script.",
            timestamp: new Date()
        };

        console.log("Pushing transcript:", testTranscript);

        const updatedCall = await Call.findOneAndUpdate(
            { _id: call._id },
            {
                $push: { transcripts: testTranscript }
            },
            { new: true }
        );

        console.log("Updated Call Transcripts Count:", updatedCall.transcripts.length);
        console.log("Last Transcript:", updatedCall.transcripts[updatedCall.transcripts.length - 1]);

        if (updatedCall.transcripts.length > 0 &&
            updatedCall.transcripts[updatedCall.transcripts.length - 1].text === testTranscript.text) {
            console.log("✅ SUCCESS: Transcript saved successfully to DB.");
        } else {
            console.error("❌ FAILURE: Transcript NOT saved.");
        }

        mongoose.disconnect();

    } catch (error) {
        console.error("Error in test script:", error);
        process.exit(1);
    }
};

testSave();
